# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Yoto' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Yoto
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
      'Core',
      'ART',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTLinkingIOS',
      'RCTGeolocation',
      'RCTImage',
      'RCTNetwork',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'DevSupport',
      # 'CxxBridge',
      # 'RCTTest'
  ]
  
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'lottie-ios', :path => '../node_modules/lottie-ios'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

end